export const primary: string = "#faf7f1";
export const title: string = "#0d285b";
export const text: string = "#fc345a";
export const dark: string = "#13131A";
export const titleSize: string = "54px"
export const subTitleSize: string = "36px"
export const textSize:string = "18px"
export const errorColor:string = "red"
export const labelSize:string = "18px"
export const label:string = "#462867"
export const sender: string = "#ff8a65";
export const reciever: string = "#0d285b";